[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  API_KEY = "From netlify.toml (movie-search_site-with-vue-for-publish-)"
 